name: Check Version

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 设置为0以获取所有历史记录和标签

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install TOML parser
        run: |
          python -m pip install --upgrade pip
          pip install toml

      - name: Get current version
        id: get-version
        run: |
          echo "VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")" >> $GITHUB_ENV

      - name: Check version change and dispatch event
        run: |
          # 获取当前版本
          CURRENT_VERSION=$VERSION
          
          # 尝试获取最后一个标签的版本
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null)
          if [[ $? -eq 0 ]]; then
            LAST_VERSION=${LAST_TAG#v}
          else
            echo "No tags found, assuming last version is 0.0.0"
            LAST_VERSION="0.0.0"
          fi
          
          # 检查版本是否更改
          if [[ "$CURRENT_VERSION" != "$LAST_VERSION" ]] && [[ "$CURRENT_VERSION" != "0.0.0" ]]; then
            echo "Version changed from $LAST_VERSION to $CURRENT_VERSION"
          
            # 触发 repository_dispatch 事件
            curl -X POST \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 https://api.github.com/repos/${{ github.repository }}/dispatches \
                 -d '{"event_type": "version-changed", "client_payload": {"version": "'"$CURRENT_VERSION"'"}}'
          else
            echo "Version did not change or version is 0.0.0"
          fi

